In [1]:
class Bill:
    rates = {"HDD":5000, "RAM":2000, "Printer":6000, "Pendrive":800}
    items = {"HDD":0, "RAM":0, "Printer":0, "Pendrive":0}
    
    for i,j in rates.items():
        print(i,j)
        accept = input("Want this item? (Y/N)").upper()
        if accept == 'Y':
            items[i] = int(input("Enter No. of "+i+" 's: '"))*rates[i]
        print()
    
    def __init__(self):
        print("1. Cash Payment")
        print("2. Cheque Payment")
        payment_method = int(input("Enter Method 1/2:"))
        if payment_method == 1:
            cashpayment()
        else:
            chequepayment()

class cashpayment(Bill):
    def __init__(self):
        print()
        print("Payment Method is Cash")
        sum=0
        for i,j in self.items.items():
            sum += j
        print("Total Amount to Pay:",sum)
        d = {"2000 Rs Notes:":2000 , "500 Rs Notes:":500 , "100 Rs Notes:":100,"200 Rs Notes:":200,
            "50 Rs Notes:":50,"20 Rs Notes:":20, "10 Rs Notes:":10}
        print()
        for i,j in d.items():
            if sum >= j:
                print(i + ":" ,sum//j)
                sum = sum%j

class chequepayment(Bill):
    def __init__(self):
        print()
        print("Payment Method is Cheque")
        sum=0
        for i,j in self.items.items():
            sum += j
        print("Total Amount to Pay:",sum)
        print()
        Chq_No = int(input("Enter Cheque Number:"))
        Bank = input("Enter Bank Name:")
        print()
        print("Cheque Details:")
        print("Cheque Number:",Chq_No)
        print("Bank Name:",Bank)
customer = Bill()    

HDD 5000
Want this item? (Y/N)n

RAM 2000
Want this item? (Y/N)n

Printer 6000
Want this item? (Y/N)n

Pendrive 800
Want this item? (Y/N)n

1. Cash Payment
2. Cheque Payment
Enter Method 1/2:1

Payment Method is Cash
Total Amount to Pay: 0



In [2]:
import numpy as np
import sys
s=range(1000)
print("Size of each element of list in bytes:",sys.getsizeof(s))
print("Size of whole list in bytes:",sys.getsizeof(s)*len(s))
print()
d=np.arange(1000)
print("Size of each element of numpy array in bytes:",d.itemsize)
print("Size of the whole numpy array in bytes:",d.size*d.itemsize)

Size of each element of list in bytes: 48
Size of whole list in bytes: 48000

Size of each element of numpy array in bytes: 4
Size of the whole numpy array in bytes: 4000


In [49]:
import numpy as np
x=np.array([1,2,3,4,5,6],ndmin=5)
print(x)
print(x.ndim)
print(x.shape)
new=x.reshape(1,6)
new=x.reshape(2,-1)
for i in np.nditer(x[:,:,::2]):
    print(i)
print(new)

[[[[[1 2 3 4 5 6]]]]]
5
(1, 1, 1, 1, 6)
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [9]:
import numpy as np
x=np.array([[1,2,3,4,5]])
print(x)
print(type(x))
print(x.ndim)
print(x[0,2])

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2
3


In [11]:
import numpy as np
x=np.array([[[1,2,3,4,5]]])
print(x)
print(type(x))
print(x.ndim)
print(x[0,0,2])

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3
3


In [17]:
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(type(x))
print(x.ndim)
print(x[1,2])

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2
7


In [50]:
import numpy as np
x=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(x)
print(type(x))
print(x.ndim)
print(x[0,1,2])
print(x[0,-1,-1])
print(x[1,1,0:3])
print(x[1:,1:,0:3])
print(x[1:])
print(x[0:2,1,1])
print(x[0:2,0:2,0:2])
for i in np.nditer(x[:,:,::2]):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
<class 'numpy.ndarray'>
3
7
8
[13 14 15]
[[[13 14 15]]]
[[[ 9 10 11 12]
  [13 14 15 16]]]
[ 6 14]
[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [13 14]]]
1
3
5
7
9
11
13
15
