concatenate()

In [7]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

array_split()

In [15]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
new=np.array_split(arr1,7)
print(new)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [19]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
new=np.array_split(arr1,3,axis=1)
print(new)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32)]


where()

In [22]:
import numpy as np
arr1=np.array([1,2,3,4,5,4,7,4,9])
x=np.where(arr1==4)
print(x)

(array([3, 5, 7], dtype=int64),)


In [29]:
import numpy as np
arr1=np.array([[1,2],[3,4],[4,5],[7,4]])
x=np.where(arr1%2==0)
print(x)

(array([0, 1, 2, 3], dtype=int64), array([1, 1, 0, 1], dtype=int64))


In [28]:
import numpy as np
arr1=np.array([[[1,2,3]],[[4,5,7]],[[1,4,3]]])
x=np.where(arr1==4)
print(x)

(array([1, 2], dtype=int64), array([0, 0], dtype=int64), array([0, 1], dtype=int64))


sort()

In [40]:
import numpy as np
arr1=np.array([1,2,3,4,5,4,3,2])
print(np.sort(arr1,axis=0))
arr2=np.array(['apple','cherry','straberry','banana'])
print(np.sort(arr2))
arr3=np.array([True,False,True])
print(np.sort(arr3))

[1 2 2 3 3 4 4 5]
['apple' 'banana' 'cherry' 'straberry']
[False  True  True]


In [45]:
import numpy as np
arr1=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr1,axis=None))

[1 2 2 3 3 4 4 5 7]


In [52]:
import numpy as np
arr1=np.array([[[3,4,2],[1,7,3]],[[5,8,7],[4,2,5]]])
print(np.sort(arr1,axis=1))

[[[1 4 2]
  [3 7 3]]

 [[4 2 5]
  [5 8 7]]]


random

In [82]:
import numpy as np
x=np.random.randint(1,100,size=(2,2,3))
print(x)

[[[82 89 43]
  [68 61 30]]

 [[68 31 69]
  [69 31 20]]]


In [98]:
import numpy as np
x=np.random.rand(3,5)
print(x)

[[0.78899968 0.91814409 0.30863527 0.73592227 0.73217197]
 [0.92354325 0.18005171 0.67807373 0.93241811 0.00388436]
 [0.96096436 0.1982638  0.94801889 0.61404256 0.94243349]]


In [116]:
import numpy as np
x=np.random.choice([1,2,3,4,5],size=5)
print(x)

[5 3 3 4 5]


In [3]:
import numpy as np
att=7
print("You have 7 attempts")
x=np.random.randint(100)
for i in range(att):
    a=int(input(("Guess no. from 1 to 100:")))
    att-=1
    print("Attempt left:",att)
    if (att==0):
        print("Game over,you lose.The number was:",x)
    elif (a==x):
        print("You guessed the number")
    elif (a>100):
        print("Invalid number")

You have 7 attempts
Guess no. from 1 to 100:67
Attempt left: 6
Guess no. from 1 to 100:34
Attempt left: 5
Guess no. from 1 to 100:56
Attempt left: 4
Guess no. from 1 to 100:23
Attempt left: 3
Guess no. from 1 to 100:45
Attempt left: 2
Guess no. from 1 to 100:58
Attempt left: 1
Guess no. from 1 to 100:90
Attempt left: 0
Game over,you lose.The number was: 18
